### ISSUE TITLE
Add "Pick a new plan" text 

### ISSUE THREAD

**Issue by jennparker** [bluebeasley/fallout-friend#14]
Display this on home page when a course isn't currently in progress
![06_homeComplete](https://user-images.githubusercontent.com/22356441/61585784-1d8fb480-ab19-11e9-94b4-651801352058.png)

**Comment by nykkole** [comment]
Currently, activity_main.xml contains the current_progress_view.xml.
We would need to dynamically change that view if there is no course currently in progress, to show no_course_in_progress.xml
Opened new issue #25
