### ISSUE TITLE
Update the course in progress image

### ISSUE THREAD

**Issue by jennparker** [bluebeasley/fallout-friend#24]
Should include course level, course title and social media pull text overlaid on top of image, as in the prototype.

Note: we might need to add an alpha to make the text pop. The prototype image is kind of a perfect case, but not all of our images are as dark as that one.

**Comment by nykkole** [comment]
Here's an article that talks about best practices for text over images https://blog.iamsuleiman.com/techniques-to-display-text-overlay-background-images/
