### ISSUE TITLE
Update "Keep Going" Sub text on home screen

### ISSUE THREAD

**Issue by jennparker** [bluebeasley/fallout-friend#4]
Is:
YOU'VE COMPLETED X/X

Should be:
"You've completed X out of X steps."

**Comment by nykkole** [comment]
@jennparker is this only about updating the string and removing the caps? If yes, then this is done. If the string should include variables to reflect the actual progress, then this is not done :)

**Comment by jennparker** [comment]
Yep, I meant the first one.  Good call - I'll write a second ticket to update those values dynamically.
